name: Build tag

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - name: Build
      run: docker build . -t tandrade/short:latest
    - name: Login
      uses: docker/login-action@v2.1.0
      with:
          username: tandrade
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Push
      run: docker push tandrade/short:latest
