name: Build tag

on:
  create:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . -t tandrade/short:${GITHUB_REF/refs\/tags\//}
    - name: Login
      uses: docker/login-action@v1.10.0
      with:
          username: tandrade
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Push
      run: docker push tandrade/short:${GITHUB_REF/refs\/tags\//}
